// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package distqueue

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DistributedQueueServiceClient is the client API for DistributedQueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DistributedQueueServiceClient interface {
	// Connect initializes a connection between the workers and leader. Workers stream items
	// to the leader and the leader will determine the order of the items
	// and send it to all connected workers. Workers will only receive messages inserted into
	// the queue after Connect is called.
	Connect(ctx context.Context, opts ...grpc.CallOption) (DistributedQueueService_ConnectClient, error)
	// GetRange returns a stream of (in order) items between the given time range.
	GetRange(ctx context.Context, in *GetRangeRequest, opts ...grpc.CallOption) (DistributedQueueService_GetRangeClient, error)
}

type distributedQueueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDistributedQueueServiceClient(cc grpc.ClientConnInterface) DistributedQueueServiceClient {
	return &distributedQueueServiceClient{cc}
}

func (c *distributedQueueServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (DistributedQueueService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &DistributedQueueService_ServiceDesc.Streams[0], "/distqueue.DistributedQueueService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &distributedQueueServiceConnectClient{stream}
	return x, nil
}

type DistributedQueueService_ConnectClient interface {
	Send(*QueueItem) error
	Recv() (*ServerQueueItem, error)
	grpc.ClientStream
}

type distributedQueueServiceConnectClient struct {
	grpc.ClientStream
}

func (x *distributedQueueServiceConnectClient) Send(m *QueueItem) error {
	return x.ClientStream.SendMsg(m)
}

func (x *distributedQueueServiceConnectClient) Recv() (*ServerQueueItem, error) {
	m := new(ServerQueueItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *distributedQueueServiceClient) GetRange(ctx context.Context, in *GetRangeRequest, opts ...grpc.CallOption) (DistributedQueueService_GetRangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &DistributedQueueService_ServiceDesc.Streams[1], "/distqueue.DistributedQueueService/GetRange", opts...)
	if err != nil {
		return nil, err
	}
	x := &distributedQueueServiceGetRangeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DistributedQueueService_GetRangeClient interface {
	Recv() (*ServerQueueItem, error)
	grpc.ClientStream
}

type distributedQueueServiceGetRangeClient struct {
	grpc.ClientStream
}

func (x *distributedQueueServiceGetRangeClient) Recv() (*ServerQueueItem, error) {
	m := new(ServerQueueItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DistributedQueueServiceServer is the server API for DistributedQueueService service.
// All implementations must embed UnimplementedDistributedQueueServiceServer
// for forward compatibility
type DistributedQueueServiceServer interface {
	// Connect initializes a connection between the workers and leader. Workers stream items
	// to the leader and the leader will determine the order of the items
	// and send it to all connected workers. Workers will only receive messages inserted into
	// the queue after Connect is called.
	Connect(DistributedQueueService_ConnectServer) error
	// GetRange returns a stream of (in order) items between the given time range.
	GetRange(*GetRangeRequest, DistributedQueueService_GetRangeServer) error
	mustEmbedUnimplementedDistributedQueueServiceServer()
}

// UnimplementedDistributedQueueServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDistributedQueueServiceServer struct {
}

func (UnimplementedDistributedQueueServiceServer) Connect(DistributedQueueService_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedDistributedQueueServiceServer) GetRange(*GetRangeRequest, DistributedQueueService_GetRangeServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRange not implemented")
}
func (UnimplementedDistributedQueueServiceServer) mustEmbedUnimplementedDistributedQueueServiceServer() {
}

// UnsafeDistributedQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistributedQueueServiceServer will
// result in compilation errors.
type UnsafeDistributedQueueServiceServer interface {
	mustEmbedUnimplementedDistributedQueueServiceServer()
}

func RegisterDistributedQueueServiceServer(s grpc.ServiceRegistrar, srv DistributedQueueServiceServer) {
	s.RegisterService(&DistributedQueueService_ServiceDesc, srv)
}

func _DistributedQueueService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DistributedQueueServiceServer).Connect(&distributedQueueServiceConnectServer{stream})
}

type DistributedQueueService_ConnectServer interface {
	Send(*ServerQueueItem) error
	Recv() (*QueueItem, error)
	grpc.ServerStream
}

type distributedQueueServiceConnectServer struct {
	grpc.ServerStream
}

func (x *distributedQueueServiceConnectServer) Send(m *ServerQueueItem) error {
	return x.ServerStream.SendMsg(m)
}

func (x *distributedQueueServiceConnectServer) Recv() (*QueueItem, error) {
	m := new(QueueItem)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DistributedQueueService_GetRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DistributedQueueServiceServer).GetRange(m, &distributedQueueServiceGetRangeServer{stream})
}

type DistributedQueueService_GetRangeServer interface {
	Send(*ServerQueueItem) error
	grpc.ServerStream
}

type distributedQueueServiceGetRangeServer struct {
	grpc.ServerStream
}

func (x *distributedQueueServiceGetRangeServer) Send(m *ServerQueueItem) error {
	return x.ServerStream.SendMsg(m)
}

// DistributedQueueService_ServiceDesc is the grpc.ServiceDesc for DistributedQueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistributedQueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distqueue.DistributedQueueService",
	HandlerType: (*DistributedQueueServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _DistributedQueueService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetRange",
			Handler:       _DistributedQueueService_GetRange_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "distqueue.proto",
}
